### ISSUE TITLE
Parent Process ID is not equal to PID of statusbar

### ISSUE THREAD

**Issue by Venem** [UtkarshVerma/dwmblocks-async#28]
Hello, I've recently started using this for my statusbar. I must say that colours and clickability work perfectly, however I do have a simple issue.

I have all of my statusbar scripts check their $PPID so that colours are only shown when the script is executed by the statusbar. This makes the scripts usable on terminals too.

The problem:
In `if [ "$(ps -p $PPID -o comm=)" = "$STATUSBAR" ]; then`,

`$STATUSBAR` is equal to `dwmblocks` and
`$(ps -p $PPID -o comm=)` is equal to `sh`

I've tried to mess around with line 84 in main.c (execBlock()) but I haven't got much experience with C.

Is it possible to make `execl("/bin/sh", "sh", "-c", blocks[i].command, (char*)NULL);` run the scripts directly rather than with `sh`?

**Comment by UtkarshVerma** [comment]
It should work now. Also, it would be better if you simply use `cat /proc/$PPID/comm`.

**Comment by Venem** [comment]
Unfortunately that didn't seem to fix it. Adding `notify-send "$(cat /proc/$PPID/comm)"` to one of the statusbar modules still returns "sh".

**Comment by Venem** [comment]
Ah ok thanks
